import click
import utilities_common.cli as clicommon
from swsscommon.swsscommon import ConfigDBConnector
from .validated_config_db_connector import ValidatedConfigDBConnector


MST_MIN_HOPS = 1
MST_MAX_HOPS = 40
MST_DEFAULT_HOPS = 20

MST_MIN_HELLO_INTERVAL = 1
MST_MAX_HELLO_INTERVAL = 10
MST_DEFAULT_HELLO_INTERVAL = 2

MST_MIN_MAX_AGE = 6
MST_MAX_MAX_AGE = 40
MST_DEFAULT_MAX_AGE = 20

MST_MIN_REVISION = 0
MST_MAX_REVISION = 65535
MST_DEFAULT_REVISION = 0

MST_MIN_BRIDGE_PRIORITY = 0
MST_MAX_BRIDGE_PRIORITY = 61440
MST_DEFAULT_BRIDGE_PRIORITY = 32768

MST_MIN_PORT_PRIORITY = 0
MST_MAX_PORT_PRIORITY = 240
MST_DEFAULT_PORT_PRIORITY = 128

MST_MIN_FORWARD_DELAY = 4
MST_MAX_FORWARD_DELAY = 30
MST_DEFAULT_FORWARD_DELAY = 15

MST_MIN_ROOT_GUARD_TIMEOUT = 5
MST_MAX_ROOT_GUARD_TIMEOUT = 600
MST_DEFAULT_ROOT_GUARD_TIMEOUT = 30

MST_MIN_INSTANCES = 0
MST_MAX_INSTANCES = 63
MST_DEFAULT_INSTANCE = 0


@click.group(cls=clicommon.AbbreviationGroup, name='spanning_tree')
def spanning_tree():
    """Multiple spanning tree related configurations"""
    pass

